org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.6.8
maven_group=com.oneworld

# Dependencies
fabric_api_version=0.157.0+26.2
modmenu_version=20.0.1
